// 基础URL
const BASE_URL = 'http://192.168.10.11:4523/m1/4705825-4357942-default'

// 获取新闻列表URL
export const URL_GET_NEWS = `${BASE_URL}/news/get`
// 获取评论列表URL
export const URL_GET_COMMENTS = `${BASE_URL}/news/comments/get`
// 获取视频列表URL
export const URL_GET_VIDEOS = `${BASE_URL}/video/get`
// 登录URL
export const URL_USER_LOGIN = `${BASE_URL}/user/login`
// 登出URL
export const USER_LOGOUT = `${BASE_URL}/user/logout`
// 更新URL
export const USER_UPDATE = `${BASE_URL}/user/update`